name: Build

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build a Docker/OCI image
    env:
      IMAGE_NAME: awscli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate a config.json
        run: |
          cat <<JSON > config.json
          {
            "auths": {
              "docker.pkg.github.com": {
                "auth": "$(echo -n :${{ secrets.GITHUB_TOKEN }} | base64)"
              }
            }
          }
          JSON
      - name: Build a image
        run: |
          docker run \
            -v $(pwd):/workspace \
            -v $(pwd)/config.json:/kaniko/.docker/config.json:ro \
            gcr.io/kaniko-project/executor:latest \
              --context dir:///workspace/ \
              --dockerfile Dockerfile \
              --cache=true \
              --cache-repo docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}-cache \
              --no-push
